const express = require('express');
const productosCtrl = require('../controllers/productos.controller');
const router = express.Router();

// Upload
const upload = require('../lib/multer.js');

// Verify token for admins
const verifyTokenUsuario = require('../lib/verify.token');

/**
 * @swagger
 * components:
 *  schemas:
 *    Producto:
 *      type: object
 *      properties:
 *          id:
 *            type: integer
 *            description: autogenerated by bd
 *          sku:
 *            type: string
 *            description: codigo del producto
 *          nombre:
 *            type: string
 *          descripcion:
 *            type: string
 *          precio:
 *            type: number
 *          stock:
 *            type: integer
 *          imagen:
 *            type: string
 *            description: URL de la imagen el el servidor
 *          idCategoria:
 *             type: integer
 *             description: idCategoria de la categoria a la que pertenece el producto
 */

/**
 * @swagger
 * tags:
 *  name: Producto
 *  description: Producto endpoint
 */

// Gestion de productos
router.post('/', verifyTokenUsuario, upload.single('imagen'), productosCtrl.createProducto);

/**
 * @swagger
 * /productos:
 *  get:
 *    summary: Return a list products
 *    tags: [Producto]
 *    responses: 
 *      200:
 *        description: the list of products
 *        content:
 *           application/json:
 *               schemas:
 *                 type: array
 *                 items:
 *                    $ref: '#/components/schemas/Producto'
 * 
 */
router.get('/', productosCtrl.getProductos);
router.get('/:idProducto', productosCtrl.getProducto)
router.put('/:idProducto', verifyTokenUsuario, productosCtrl.updateProducto)
router.delete('/:idProducto', verifyTokenUsuario, productosCtrl.deleteProducto)

module.exports = router;

// SWAGGER:  https://www.youtube.com/watch?v=9bO0L1rfkvU